from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_wn_Hubs(object):
    def setupUi(self, wn_Hubs):
        wn_Hubs.setObjectName(_fromUtf8("wn_Hubs"))
        wn_Hubs.resize(578, 324)
        wn_Hubs.setStyleSheet("Color: white;font-size:16px;")
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 129, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 129, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 129, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 129, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        wn_Hubs.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        wn_Hubs.setFont(font)
        self.listView = QtGui.QListView(wn_Hubs)
        self.listView.setGeometry(QtCore.QRect(30, 100, 256, 151))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.listView.setStyleSheet("background-color:white;Color: black; font-size:12px;")
        self.label = QtGui.QLabel(wn_Hubs)
        self.label.setGeometry(QtCore.QRect(30, 80, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(wn_Hubs)
        self.groupBox.setGeometry(QtCore.QRect(300, 100, 241, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 50, 201, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit.setStyleSheet("background-color:white;Color: black; font-size:12px;")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 111, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.bt_Add_Hub = QtGui.QPushButton(self.groupBox)
        self.bt_Add_Hub.setGeometry(QtCore.QRect(20, 120, 75, 23))
        self.bt_Add_Hub.setStyleSheet("background-color:#dddddd;Color: black; font-size:12px;")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bt_Add_Hub.setFont(font)
        self.bt_Add_Hub.setObjectName(_fromUtf8("bt_Add_Hub"))
        self.label_3 = QtGui.QLabel(wn_Hubs)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 161, 41))
        self.label_3.setStyleSheet("font-size:20px;")
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))

        self.retranslateUi(wn_Hubs)
        QtCore.QMetaObject.connectSlotsByName(wn_Hubs)

    def retranslateUi(self, wn_Hubs):
        wn_Hubs.setWindowTitle(_translate("wn_Hubs", "Hubs", None))
        self.label.setText(_translate("wn_Hubs", "Current Hubs", None))
        self.groupBox.setTitle(_translate("wn_Hubs", "Add New Hub", None))
        self.label_2.setText(_translate("wn_Hubs", "Hub name", None))
        self.bt_Add_Hub.setText(_translate("wn_Hubs", "Add Hub", None))
        self.label_3.setText(_translate("wn_Hubs", "Add New Hub", None))